youtoxic/app/__init__.py
import matplotlib

matplotlib.use("TkAgg")

youtoxic/app/routes.py
"""Contains routes for the flask app.

"""
from flask import Blueprint, render_template


main_bp = Blueprint(
    "main_bp", __name__, template_folder="templates", static_folder="static"
)


@main_bp.route("/", methods=["GET"])
@main_bp.route("/index")
def index():
    return render_template("index.html", title="YouToxic", template="home_template")

youtoxic/app/templates/enter_text.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Basic Analysis</h1>
    <br>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

youtoxic/app/templates/enter_twitter_username.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Search by Twitter Username</h1>
    <br>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

youtoxic/app/templates/index.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main_bp.index') }}">YouToxic</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('/dash/') }}">App</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <style>
        footer {bottom: 0; position: fixed; text-align: center;}
    </style>
    <a href="{{ url_for('/dash/') }}">YouToxic App</a>
    <footer>Work in Progress – Created by Julius Hochmuth</footer>
{% endblock %}

youtoxic/app/templates/result.html
{% extends 'base.html' %}

{% block app_content %}
    <h1>Results of Analysis</h1>
    <br>
    <p>Text analyzed: {{ text }}</p>
    <br>
    {% for type in types %}
        <p>{{ type }} classification: <div id="judgement">{{ classes[type] }}</div></p>
        <p>{{ type }} prediction: <div id="prediction">{{ preds[type] }}</div></p>
        <br>
    {% endfor %}
    <a href="{{ url_for('get_texts') }}">Analyze another comment</a>
{% endblock %}

youtoxic/app/templates/results_tweets.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <table border="1">
        <tr>
            <td align="center">Time Posted</td>
            <td align="center">Text of Tweet</td>
            {% for type in pred_types %}
                <td align="center">{{ type }}</td>
                <td align="center">{{ type }} prediction </td>
            {% endfor %}
        </tr>
        {% for id, time, text in tweets %}
            {% set outer_loop = loop.index-1 %}
            {% set any_toxic = [] %}
            {% if display == 'toxic' %}
                {% for type in pred_types %}
                    {% if preds[type][outer_loop] > 0.4 %}
                        {% do any_toxic.append(1) %}
                    {% endif %}
                {% endfor %}
            {% else %}
                {% do any_toxic.append(1) %}
            {% endif %}
            {% if any_toxic %}
                <tr>
                <td align="center">{{ time }}</td>
                <td>{{ text }}</td>
                {% for type in pred_types %}
                    <td width="100px" align="center">{{ classes[type][outer_loop] }}</td>
                    <td width="50px" align="center">{{ preds[type][outer_loop] }}</td>
                {% endfor %}
                </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endblock %}

youtoxic/app/templates/return_tweets.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Analyze the following tweets?</h1>
    <br>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <table border="1">
        {% for id, time, text in tweets %}
            <tr>
                <td>{{ time }}</td>
                <td>{{ text }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}